apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: student-help-desk-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: chinmaycp/student-help-desk:latest
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_USER
          value: "phpuser"
        - name: DB_PASSWORD
          value: "phppassword"
        - name: DB_NAME
          value: "php_app_db"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: student-help-desk-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: backend

