name: CI/CD Pipeline for Kubernetes Deployment

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Build Docker images
    - name: Build Docker Image
      run: |
        docker build -t chinmaycp/student-help-desk:latest .

    # Step 4: Push images to Docker Hub
    - name: Login to Docker hub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Image
      run: |
        docker push chinmaycp/student-help-desk:latest

    # Step 5: Apply Kubernetes manifests
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f backend.yaml
        kubectl apply -f frontend.yaml
        kubectl apply -f mysql-data.yaml
